### ISSUE TITLE
请不要在linux下尝试

### ISSUE THREAD

**Issue by chaosky** [ethanfu/Documents#1]
目前Intellij在linux下字体渲染有问题, 锯齿非常严重. 通过修改 .vmoptions 添加 -Dawt.useSystemAAFontSettings=lcd -Dswing.aatext=true 参数解决了窗体控件的字体, 基本上和系统一致了. 但是 Editor(编辑器)里的字体还是有锯齿, 修改Settings -> Editor 里的antialiasing 选项毫无用处. 猜测可以通过修改jdk的字体配置来修正这个问题, 但是代价太高会影响到所有的java程序, 只好作罢.

我的环境是 Intellij 12, Ubuntu 12.04 x64, jdk 1.7b17_x64

还请po主在文章中提示一下, 省的其他人再浪费时间了.

![ _006](https://f.cloud.github.com/assets/1270629/390631/f09014e4-a745-11e2-911e-ede4daa3682e.png)

**Comment by ethanfu** [comment]
这个好似是中文字体有锯齿,等我也在ubuntu上试试

**Comment by ethanfu** [comment]
我测试了，我是使用了Ubuntu，然后桌面是使用了KDE，装了中文字体以后我的效果是这样的，我觉得还可以，如图
![ 1](https://f.cloud.github.com/assets/1206522/395280/09e922b8-a7f6-11e2-91f5-fae737e00cd1.png)

**Comment by chaosky** [comment]
你使用的是什么字体? 我用的是文泉驿的, 主界面表现能接受, 编辑器看时间长了眼花. 我桌面是默认的Unity

**Comment by ethanfu** [comment]
这个我用的是KDE的默认字体，这个更多的是系统渲染的问题，默认效果还是可以接受的，unity我没用过改天可以试试
