### ISSUE TITLE
楼主能写些maven在IDEA中得技巧..debug那些的...期待着

### ISSUE THREAD

**Issue by notedown** [ethanfu/Documents#2]
楼主最好写些maven在IDEA中得技巧..debug那些的...期待着
这个地址也是别人更新的技巧..不过这些大部分都是前端开发的人https://github.com/damao/Intellij-IDEA-F2E

**Comment by ethanfu** [comment]
技巧其实有一些可以写，但是debug这种没啥技巧吧？本身工具的话其实能做的不多。如果你有的话可以写一篇，一起搞个合集
