### ISSUE TITLE
请问如何在idea中引用maven工程而不是静态jar呢？

### ISSUE THREAD

**Issue by ChangeLeon** [ethanfu/Documents#4]
如题，想请问楼主，我在idea的maven工程中引入了parent，并且添加了dependencies，但是远程仓库中的dependencies jar包版本太低，公司并没有及时更新，现在我打算像在myeclipse中一样，想让当前工程依赖dependencies工程，而不是静态jar，不知道如何设置，能指教下吗？

**Comment by ethanfu** [comment]
这个好似 IDEA 还真不好做到呢，如果不是同一个 project 的 moudle 的情况下。我们一般都是把你依赖的 dependencies 先 mvn install 到本地。

**Comment by ChangeLeon** [comment]
嗯。谢谢回答
